name: Create Jira Ticket on Commit

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Jira Ticket
        env:
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ACCOUNT_ID: ${{ secrets.JIRA_ACCOUNT_ID }}  # Store the valid account ID in GitHub Secrets
        run: |

          curl --http1.1 --request POST \
            --url "https://$JIRA_DOMAIN/rest/api/3/issue" \
            --header "Authorization: Basic $JIRA_API_TOKEN" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "fields": {
                "project": { "key": "SCRUM" },
                "issuetype": { "name": "Bug" },
                "reporter": { "accountId": "'"$JIRA_ACCOUNT_ID"'" },
                "summary": "New Commit: '${{ github.sha }}'",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                          "text": "A new commit was made. Commit message: ${{ github.event.head_commit.message }}"
                        }
                      ]
                    }
                  ]
                }
              }
            }'
