name: Create Jira Ticket on Commit

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Jira Ticket
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}  # Your Jira API token
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}          # Your Jira email
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}        # Your Jira domain (e.g., your-domain.atlassian.net)
        run: |
          curl --request POST \
            --url "https://$JIRA_DOMAIN/rest/api/3/issue" \
            --header "Authorization: Basic $(echo -n "$JIRA_EMAIL:$JIRA_API_TOKEN" | base64)" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data '{
              "fields": {
                "project": {
                  "key": "SCRUM"  # Replace with your Jira project key
                },
                "issuetype": {
                  "name": "Bug"  # Replace with your issue type
                },
                "reporter": {
                  "accountId": "712020:59136aa2-b1f5-4776-b4d9-2dbf8b9e3e08"  # Replace with actual reporter's accountId
                },
                "summary": "New Commit: '${{ github.sha }}'",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                          "text": "A new commit was made to the repository. Commit message: ${{ github.event.head_commit.message }}"
                        }
                      ]
                    }
                  ]
                }
              }
            }'
